version: 2.1
jobs:
  deploy_admin:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout

      - run:
          name: npm install
          command: npm install
      - run:
          name: npm build
          command: npm run build
      - run:
          name: deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive


workflows:
  version: 2
  deploy:
    jobs:
      - deploy_admin:
          filters:
            branches:
              only: master
