version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: install firebase tools
          command: sudo yarn global add firebase-tools
      - run:
          name: install
          command: yarn install
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: install firebase tools
          command: sudo yarn global add firebase-tools
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive


workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: production
