version: 2.1
jobs:
  deploy_admin:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: install firebase tools
          command: sudo npm install -g firebase-tools
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm build
          command: npm run build
      - run:
          name: deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive


workflows:
  version: 2
  deploy:
    jobs:
      - deploy_admin:
          filters:
            branches:
              only: master
